#!/bin/bash
cd /home/user/wt/x1
. ./.envrc
HOOKS="AITEST AMBIENTTEST AUDIOGATE AUDIOTEST BEACONTEST BENCHTEST CDTEST CODEXTEST COMBATTEST CONCEALTEST CONTRACTTEST COVERTEST DEATHTEST DKTEST DOWNTEST DRAFTTEST EVENTTEST EXPOSURETEST FIELDTEST HAZARDTEST HEATLADDERTEST HORDETEST ITEMTEST METATEST MODETEST MORALETEST OWTEST PIKETEST PODTEST RESCUETEST SAVETEST SCARTEST SHOVETEST SIEGETEST SNAPTEST STAGGERTEST STATUSTEST THREATTEST TRAITTEST TUTTEST VETTEST WOUNDTEST"
FAILS=0
for h in $HOOKS; do
  OUT=$(env "SIGHTLINE_$h=1" ./bin/Release/net8.0/Sightline 2>&1 | tail -20)
  if echo "$OUT" | grep -q "PASS"; then
    if echo "$OUT" | grep -q "FAIL"; then echo "MIXED $h: $OUT"; FAILS=$((FAILS+1));
    else echo "PASS  $h"; fi
  else
    echo "FAIL  $h :: $(echo "$OUT" | tail -6)"; FAILS=$((FAILS+1))
  fi
done
echo "BATTERY FAILS=$FAILS"
